In [26]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from numpy import transpose as T

In [27]:
min_temp = np.array([7.9,7.8,7.4,8.5,10.1,12,14.3,15.6,16.4,15.1,12.7,10.2])
max_temp = np.array([11.4,10.4,10,11.2,12.7,14.8,16.2,17.9,18.1,17.3,15.9,13.4])
dfw = pd.DataFrame([min_temp, max_temp])
dfw = dfw.T
dfw = dfw.rename(columns={0:'Min', 1:'Max'})
dfw

Min   Max
0    7.9  11.4
1    7.8  10.4
2    7.4  10.0
3    8.5  11.2
4   10.1  12.7
5   12.0  14.8
6   14.3  16.2
7   15.6  17.9
8   16.4  18.1
9   15.1  17.3
10  12.7  15.9
11  10.2  13.4

In [28]:
dfw['Mean'] = dfw.Min + ((dfw.Max-dfw.Min)/2)
dfw

Min   Max   Mean
0    7.9  11.4   9.65
1    7.8  10.4   9.10
2    7.4  10.0   8.70
3    8.5  11.2   9.85
4   10.1  12.7  11.40
5   12.0  14.8  13.40
6   14.3  16.2  15.25
7   15.6  17.9  16.75
8   16.4  18.1  17.25
9   15.1  17.3  16.20
10  12.7  15.9  14.30
11  10.2  13.4  11.80

In [29]:
dfw['Std'] = dfw.std(axis=1)

In [30]:
dfw['n_days'] = [31,28,31,30,31,30,31,31,30,31,30,31]
dfw


Min   Max   Mean   Std  n_days
0    7.9  11.4   9.65  1.75      31
1    7.8  10.4   9.10  1.30      28
2    7.4  10.0   8.70  1.30      31
3    8.5  11.2   9.85  1.35      30
4   10.1  12.7  11.40  1.30      31
5   12.0  14.8  13.40  1.40      30
6   14.3  16.2  15.25  0.95      31
7   15.6  17.9  16.75  1.15      31
8   16.4  18.1  17.25  0.85      30
9   15.1  17.3  16.20  1.10      31
10  12.7  15.9  14.30  1.60      30
11  10.2  13.4  11.80  1.60      31

In [31]:
31*16*12

5952

In [32]:
dfw['cells_per_day'] = dfw['n_days'].apply(lambda x: x*12)
dfw

Min   Max   Mean   Std  n_days  cells_per_day
0    7.9  11.4   9.65  1.75      31            372
1    7.8  10.4   9.10  1.30      28            336
2    7.4  10.0   8.70  1.30      31            372
3    8.5  11.2   9.85  1.35      30            360
4   10.1  12.7  11.40  1.30      31            372
5   12.0  14.8  13.40  1.40      30            360
6   14.3  16.2  15.25  0.95      31            372
7   15.6  17.9  16.75  1.15      31            372
8   16.4  18.1  17.25  0.85      30            360
9   15.1  17.3  16.20  1.10      31            372
10  12.7  15.9  14.30  1.60      30            360
11  10.2  13.4  11.80  1.60      31            372

In [33]:
t_obs = [np.random.normal(i,j,k) for i,j,k in zip(dfw['Mean'],dfw['Std'], dfw['cells_per_day'])]

In [34]:
t_obs_rav = np.ravel(t_obs).tolist()

c:\Users\delst\anaconda3\lib\site-packages\numpy\core\_asarray.py:171: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return array(a, dtype, copy=False, order=order, subok=True)


- Here we have created an array of normal distribution samples for sea temperatures.
- Min and Max values of sea temperatures are taken per month.
- A normal distribution has been created for each month.
- A random sample is extracted 31*16 times (days in a month * 4 * observations of engines per day).
- This creates the correct number of temperature observations for 1 years.
- We have 12 years and 3 months of observations. (12.25 years)
- Therefore we repeat this operation 12.25 times

In [35]:
print(len(t_obs[0]))
print(496/16)

372
31.0


In [36]:
t_obs_full = np.tile(t_obs, 13)
t_obs_full

c:\Users\delst\anaconda3\lib\site-packages\numpy\lib\shape_base.py:1250: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  c = _nx.array(A, copy=False, subok=True, ndmin=d)


array([array([11.30212322,  9.90347978, 10.56696472,  7.44470875,  6.59279175,
              10.71888478,  8.37324984,  9.2984255 ,  9.53474676, 11.59248795,
               9.43420204,  9.72071675, 11.90483106,  8.80490855,  9.6990876 ,
               8.89737106,  8.5090147 ,  6.6606776 , 12.22624675, 10.33128839,
              10.68568838, 10.21810465, 11.93475413, 11.86700857,  8.47167896,
               7.46474297, 10.79852885,  8.67354629,  9.76338533,  8.30067051,
              10.07756571, 10.78569828, 11.66271205, 10.14296374, 11.01340514,
              10.99759224,  9.61699861,  9.17906587,  8.38092621, 10.34979264,
               9.99543509, 11.02728187, 12.47650503,  9.46395982,  8.52971514,
              11.39034825, 10.55550104, 10.31419842,  9.37760773,  8.0187605 ,
               9.6045164 ,  9.76175584,  7.555517  , 10.09401834,  6.69006876,
              10.1456563 ,  7.10576658,  9.71976926, 12.43408501, 11.70997816,
              13.81292916, 13.67591544,  5.20038077,

In [37]:
print(len(t_obs))
len(t_obs_full)

12


156

- Above, we have created 13 years worth of data. We only require 12.25 years worth. Therefore, we will delete samples for > March 2022

In [38]:
# new = np.delete(t_obs_full, np.s_[147:156], axis = 0)
# len(new)
# new

- We will now stack the data so it can be easily inputted to the original dataframe.
- Validation can now be conducted easily.

In [39]:
a = np.concatenate(t_obs_full).ravel()
print(len(a))
a

56940


array([11.30212322,  9.90347978, 10.56696472, ..., 10.26650738,
        9.41687284, 12.11773374])

In [40]:
new = [np.random.normal(i,0.25,16) for i in a]
new = [n.round(1) for n in new]

print(len(new))
new

new

56940


[array([11.3, 11.1, 11.6, 11.3, 11.7, 11.6, 11.2, 11.2, 12. , 11.2, 11. ,
        11. , 11.1, 11. , 11.2, 11.5]),
 array([ 9.9, 10. , 10.2,  9.6,  9.8, 10.1,  9.9,  9.8,  9.7,  9.9,  9.9,
        10.1,  9.7,  9.9, 10.3, 10.1]),
 array([10.6, 10.7, 10.7, 10.5, 10.7, 10.5, 10.3, 10.7, 10.6, 10.4, 10.3,
        11.1, 10.3, 10.3, 10.6, 10.8]),
 array([7.3, 7.5, 7.6, 7.3, 7.3, 7.1, 7.4, 8.2, 7.6, 7.8, 7.3, 7.2, 7.4,
        7.5, 7.5, 6.9]),
 array([6.7, 6.8, 6.8, 6.8, 6.9, 6.5, 6.6, 6.5, 6.3, 6.6, 6.8, 6.7, 6.7,
        6.6, 6.6, 5.9]),
 array([11. , 10.8, 10.9, 10.6, 10.6, 10.8, 10.7, 10.8, 10.6, 10.5, 10.3,
        10.8, 11.1, 10.9, 10.5, 10.7]),
 array([8.2, 8.1, 8. , 8.3, 8.4, 8. , 8.4, 8.3, 8.6, 8.1, 8.4, 8.3, 8.1,
        8.3, 8. , 8.3]),
 array([9.5, 9. , 9.2, 9.2, 9.3, 9.3, 8.9, 9.3, 8.7, 9.5, 9.3, 9.4, 9.1,
        9.8, 9.3, 9.2]),
 array([9.3, 9.6, 9.5, 9.5, 9.9, 9.5, 9.3, 9.5, 9.8, 9.3, 9.8, 9.8, 9.2,
        9.5, 9.2, 9.2]),
 array([11.7, 11.7, 11.5, 11.4, 11.8, 11.7, 11.9, 11.6

In [41]:
temp = np.concatenate(new).ravel()
len(temp)

911040

In [42]:
temp = temp[0:858816]
len(temp)

858816

In [55]:
x = pd.DataFrame(temp, columns=['temp'])
x

temp
0       11.3
1       11.1
2       11.6
3       11.3
4       11.7
...      ...
858811   9.9
858812   9.5
858813   9.4
858814   9.1
858815   8.9

[858816 rows x 1 columns]

In [ ]:
x.to_excel('Sea_Temp_Data.xlsx', index=True, header=True)

---

In [44]:
dfw

Min   Max   Mean   Std  n_days  cells_per_day
0    7.9  11.4   9.65  1.75      31            372
1    7.8  10.4   9.10  1.30      28            336
2    7.4  10.0   8.70  1.30      31            372
3    8.5  11.2   9.85  1.35      30            360
4   10.1  12.7  11.40  1.30      31            372
5   12.0  14.8  13.40  1.40      30            360
6   14.3  16.2  15.25  0.95      31            372
7   15.6  17.9  16.75  1.15      31            372
8   16.4  18.1  17.25  0.85      30            360
9   15.1  17.3  16.20  1.10      31            372
10  12.7  15.9  14.30  1.60      30            360
11  10.2  13.4  11.80  1.60      31            372

In [45]:
inc = (1.1-0.9)/24
inc

0.008333333333333337

In [46]:
   # Warmest = 15,   Coldest = 6
hours = np.array([5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,0,1,2,3,4])

In [47]:
hourly_temp1 = np.arange(0.9,1.1, inc*2)
hourly_temp2 = np.flip(hourly_temp1)
hourly_temp = np.concatenate((hourly_temp1, hourly_temp2))

print(len(hourly_temp))
hourly_temp

24


array([0.9       , 0.91666667, 0.93333333, 0.95      , 0.96666667,
       0.98333333, 1.        , 1.01666667, 1.03333333, 1.05      ,
       1.06666667, 1.08333333, 1.08333333, 1.06666667, 1.05      ,
       1.03333333, 1.01666667, 1.        , 0.98333333, 0.96666667,
       0.95      , 0.93333333, 0.91666667, 0.9       ])

In [48]:
df_hour = pd.DataFrame([hours,hourly_temp]).T
df_hour = df_hour.rename(columns={0:'Hour',1:'Temp'})
df_hour

Hour      Temp
0    5.0  0.900000
1    6.0  0.916667
2    7.0  0.933333
3    8.0  0.950000
4    9.0  0.966667
5   10.0  0.983333
6   11.0  1.000000
7   12.0  1.016667
8   13.0  1.033333
9   14.0  1.050000
10  15.0  1.066667
11  16.0  1.083333
12  17.0  1.083333
13  18.0  1.066667
14  19.0  1.050000
15  20.0  1.033333
16  21.0  1.016667
17  22.0  1.000000
18  23.0  0.983333
19   0.0  0.966667
20   1.0  0.950000
21   2.0  0.933333
22   3.0  0.916667
23   4.0  0.900000

---

In [49]:
name_data = np.ravel(new).tolist()
x = pd.DataFrame(name_data, columns=['temp'])
x

temp
0       11.3
1       11.1
2       11.6
3       11.3
4       11.7
...      ...
911035  12.0
911036  11.9
911037  12.1
911038  12.4
911039  12.4

[911040 rows x 1 columns]

In [50]:
x.describe()

temp
count  911040.000000
mean       12.818621
std         3.259775
min         3.100000
25%        10.100000
50%        12.700000
75%        15.700000
max        20.600000